services:
  - type: web
    name: n8n
    env: docker
    plan: free
    autoDeploy: false
    region: frankfurt
    disks:
      - name: n8n-data
        mountPath: /home/node/.n8n
        sizeGB: 1
